repos:
  # Rust format
  - repo: local
    hooks:
      - id: rustfmt
        name: Rust Formatter
        description: Format rust files within workspace
        entry: cargo fmt --all
        language: system
        pass_filenames: false

  # Rust linting (Clippy)
  - repo: local
    hooks:
      - id: clippy
        name: Rust Linter (Clippy)
        description: Check for warnings and best practices
        entry: cargo clippy -- -D warnings
        language: system
        pass_filenames: false
